version: '3.8'

services:
  database:
    container_name: database
    # use build for development
    # build: ./server/database
    # use image instead of build otherwise
    image: chrish14/dash_db
    ports:
      - '5432:5432'
    networks:
      - app-network
  server:
    container_name: server
    # use build for development
    # build: ./
    # use image instead of build otherwise
    image: chrish14/dash_server:v3
    working_dir: /usr/src/app
    ports:
      - '3001:3001'
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_DB
    networks:
      - app-network
    entrypoint: ['npm', 'run', 'server']
    # comment in volumes for development
    # volumes:
    #   - ./:/usr/src/app
    depends_on:
      - database
networks:
  app-network:
    driver: bridge
