version: '3.8'

services:
  database:
    container_name: database
    build: server/database
    ports:
      - '5432:5432'
    networks:
      - app-network
  server:
    container_name: server
    build: ./
    working_dir: /usr/src/app
    ports:
      - '3001:3001'
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_DB
    networks:
      - app-network
    entrypoint: ['npm', 'run', 'server']
    volumes:
      - ./:/usr/src/app
    depends_on:
      - database
networks:
  app-network:
    driver: bridge
